### ISSUE TITLE
how to decrypt ?

### ISSUE THREAD

**Issue by ittech25** [LordGhostX/LGXCrypt#1]
Script Encrypt working Fine. i very like it
But how to decrypt files ?

Please upload file decrypt or help me

Thanks

**Comment by LordGhostX** [comment]
Run the script again, but this time pass a different mode other than E
![image](https://user-images.githubusercontent.com/47832826/79528786-d4966d80-8062-11ea-898d-a93662ffbeed.png)
change start(mode="E") to start(mode="D")

**Comment by ittech25** [comment]
Thank you @LordGhostX
